# Generated by Django 3.0 on 2020-04-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('ph_number', models.IntegerField(max_length=12)),
                ('image', models.ImageField(upload_to='pics')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
